
function display_manual
{
echo "   !!========================================================================!!"
echo "   !! [0] - CHANGE THE NAME                                                  !!" 
echo "   !!  --[0.0] ADD {what,where}                                              !!" 
echo "   !!            |                                                           !!"
echo "   !!            |                                                           !!" 
echo "   !!            |---[0.0.0] -- to the front                                 !!"  
echo "   !!            |---[0.0.9] -- to the back with extension                   !!"  
echo "   !!            |---[0.0.8] -- to the back without extension                !!"  
echo "   !!                                                                        !!"
echo "   !!                                                                        !!"
echo "   !!  --[0.9] REMOVE                                                        !!" 
echo "   !!               |                                                        !!" 
echo "   !!               --[0.9.0] NUMBER OF CHARACTERS from front                !!"    
echo "   !!               |                                                        !!"
echo "   !!               --[0.9.9] STRING                                         !!" 
echo "   !!                                                                        !!"
echo "   !!  --[0.8] MODIFY                                                        !!" 
echo "   !!               |                                                        !!" 
echo "   !!               --[0.8.0] INCREMENT A SERIES OF FOLDERS                  !!" 
echo "   !!               --[0.8.9] MODIFY STRINGS                                 !!" 
echo "   !!               --[0.8.8] RENAME PHOTOS LIKE (R@@ M@@ D@@                !!" 
echo "   !!               --[0.8.7] RENAME PHOTOS FROM 1 TO N                      !!" 
echo "   !!                                                                        !!"
echo "   !!========================================================================!!"
echo "   !! [9] - MAC OPERATIONS                                                   !!" 
echo "   !!  |                                                                     !!" 
echo "   !!  -- [9.0]MAKE THE DOCK DELAY 0                                         !!" 
echo "   !!  -- [9.9] CHANGR THE PATH FOR SCREENSHOTS                              !!" 
echo "   !!  -- [9.8]HIDDEN FILES                                                  !!" 
echo "   !!               |                                                        !!" 
echo "   !!               --[9.9.0] SHOW                                           !!" 
echo "   !!               --[9.9.9] HIDE                                           !!" 
echo "   !!========================================================================!!"
echo "   !! [8] - IMAGE MANIPULATION[REQUIRES IMAGE MAGIC]                         !!" 
echo "   !!  |                                                                     !!" 
echo "   !!  -- [8.0] CROP                                                         !!"
echo "   !!  -- [8.9] MERGE                                                        !!"
echo "   !!               |                                                        !!" 
echo "   !!               --[8.9.0] ||| VERTICAL                                   !!" 
echo "   !!               --[8.9.9] --- HORIZONTAL                                 !!" 
echo "   !!                                                                        !!"
#echo "   !! [7] - CREATE                                                          !!"
#echo "   !!  |                                               ="
echo "   !!========================================================================!!"
echo "   !! [7] - CONVERT .mov to .mp4  [REQUIRES "ffmpeg" ]                        !!" 
echo "   ============================================================================"
}
